### ISSUE TITLE
Broken external links (point internally instead of pointing to the right absolute location)

### ISSUE THREAD

**Issue by adisarid** [rstudio-education/teach-shiny#3]
Hi Mine,
Thank you for the wonderful workshop!

I was checking the links you posted for the dropbox folder, but they don't work. 
(Ironically, then I tried the "report an issue" link (on the right navbar), but it didn't work either).

Anyway, the links don't work because they are not absolute. I.e., external links in your pages are appended with the base domain as if they were internal to the domain.

For example, the link to the dropbox folder appears as: [http://teach-shiny.rbind.io/post/rstd.io/shiny-sample-curricula](http://teach-shiny.rbind.io/post/rstd.io/shiny-sample-curricula) instead of what you meant:
[https://rstd.io/shiny-sample-curricula](https://rstd.io/shiny-sample-curricula).

Same for additional external links such as report issues, suggest an edit, and maybe some more...

**Comment by mine-cetinkaya-rundel** [comment]
Thank you, these should be fixed, and the fixes should propagate to the live website shortly!
